version: "3.8"

services:
  course-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bunny_course_streaming_backend

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "5000:5000"

    depends_on:
      postgres-db:
        condition: service_healthy

    volumes:
      - ./uploads:/home/app/uploads
      - ./public/output:/home/app/public/output

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - backend

  postgres-db:
    image: postgres:16-alpine

    container_name: bunny_course_streaming_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: